/**
 * Video Download API Route
 * Handles video downloads from URLs using yt-dlp
 */

import { NextResponse } from 'next/server';
import VideoDownloaderService from '@/app/lib/video-processing/services/downloaderService';
import VideoUtils from '@/app/lib/video-processing/utils/videoUtils';

const downloaderService = new VideoDownloaderService();

export async function POST(request) {
  try {
    const { url, options = {} } = await request.json();

    if (!url) {
      return NextResponse.json(
        { error: 'URL is required' },
        { status: 400 }
      );
    }

    // Validate URL format
    if (!downloaderService.isValidUrl(url)) {
      return NextResponse.json(
        { error: 'Invalid URL format' },
        { status: 400 }
      );
    }

    // Check if platform is supported
    const platform = downloaderService.detectPlatform(url);
    if (!platform) {
      return NextResponse.json(
        { error: 'Unsupported video platform. Supported platforms: YouTube, Twitch, Kick, Rumble, Vimeo' },
        { status: 400 }
      );
    }

    // Get video info first (without downloading)
    let videoInfo;
    try {
      videoInfo = await downloaderService.getVideoInfo(url);
    } catch (error) {
      return NextResponse.json(
        { 
          error: 'Failed to get video information',
          details: error.message 
        },
        { status: 400 }
      );
    }

    // Validate video constraints
    const constraints = VideoUtils.getPlatformConstraints(options.targetPlatform || 'tiktok');
    const validation = VideoUtils.validateProcessingConstraints(videoInfo, {
      maxDuration: options.maxDuration || constraints.maxDuration * 2, // Allow longer videos for clipping
      maxFileSize: options.maxFileSize || 1073741824 // 1GB default
    });

    if (!validation.isValid) {
      return NextResponse.json(
        { 
          error: 'Video does not meet processing requirements',
          issues: validation.issues,
          videoInfo: {
            title: videoInfo.title,
            duration: VideoUtils.formatDuration(videoInfo.duration),
            fileSize: VideoUtils.formatFileSize(videoInfo.filesize || 0)
          }
        },
        { status: 400 }
      );
    }

    // Download the video
    const downloadResult = await downloaderService.downloadVideo(url, {
      quality: options.quality || 'best[height<=1080]/best',
      audioOnly: options.audioOnly || false,
      downloadSubtitles: options.downloadSubtitles || false,
      autoGeneratedSubs: options.autoGeneratedSubs || false,
      outputFormat: options.outputFormat || 'mp4',
      maxFileSize: options.maxFileSize || '1G',
      maxDuration: options.maxDuration || 7200
    });

    const response = {
      success: true,
      download: downloadResult,
      videoInfo: videoInfo,
      platform: platform,
      qualityScore: VideoUtils.calculateQualityScore(videoInfo),
      processing: {
        estimatedClips: Math.ceil(videoInfo.duration / 60), // Rough estimate
        recommendedPlatforms: VideoUtils.getPlatformConstraints(platform) ? [platform] : ['tiktok'],
        canProcess: validation.isValid
      }
    };

    return NextResponse.json(response);

  } catch (error) {
    console.error('Download error:', error);
    
    return NextResponse.json(
      { 
        error: 'Download failed',
        details: error.message 
      },
      { status: 500 }
    );
  }
}

export async function GET(request) {
  try {
    const { searchParams } = new URL(request.url);
    const url = searchParams.get('url');

    if (!url) {
      return NextResponse.json(
        { error: 'URL parameter is required' },
        { status: 400 }
      );
    }

    // Get video information without downloading
    const videoInfo = await downloaderService.getVideoInfo(url);
    const platform = downloaderService.detectPlatform(url);
    
    const response = {
      success: true,
      videoInfo: videoInfo,
      platform: platform,
      qualityScore: VideoUtils.calculateQualityScore(videoInfo),
      constraints: VideoUtils.getPlatformConstraints(platform),
      canDownload: !!platform,
      estimatedFileSize: VideoUtils.formatFileSize(videoInfo.filesize || 0),
      formattedDuration: VideoUtils.formatDuration(videoInfo.duration || 0)
    };

    return NextResponse.json(response);

  } catch (error) {
    console.error('Video info error:', error);
    
    return NextResponse.json(
      { 
        error: 'Failed to get video information',
        details: error.message 
      },
      { status: 500 }
    );
  }
}

// Health check for downloader service
export async function HEAD(request) {
  try {
    const isHealthy = await downloaderService.healthCheck();
    
    if (isHealthy) {
      return new Response(null, { status: 200 });
    } else {
      return new Response(null, { status: 503 });
    }
  } catch (error) {
    return new Response(null, { status: 500 });
  }
}